### ISSUE TITLE
New 버튼 이외에 UI가 뜨지 않습니다.

### ISSUE THREAD

**Issue by MoorDev** [dmc31a42/UnityL10nTool#10]
TheRoom two라는 게임을 한글화하고 있습니다. (Unity 5.3기반)그런데 이 게임이 NGUI의 비트맵폰트 방식이라 한글폰트 주입이 필요합니다.

마침 해당툴이 한글폰트 주입이 가능하다해서 사용하려고 하는데 New버튼을 누르고 exe가 있는 곳을 선택해도 아무런 반응이 없군요.

다른 사람들을 보니 UI가 이것저것 뜨는데 일부라이브러리가 부족한것인지 아니면 제 시스템에 문제가 있는 것인지 알 수가 없습니다.

Windows7 Home x64이며
.Net Framework 4.7.2
Visual C++ Runtime은 x64버전으로 2010 2012 2013 2015 2018이 설치된 상황입니다.

필수 라이브러리가 무엇이 있는지 알려주신다면 감사하겠습니다.

**Comment by MoorDev** [comment]
app.info파일이 없어서 그런것이군요!
감사합니다.
NGUI폰트엔진도 지원해주신다고 하니 정말 감사드립니다. 
NGUI로 비트맵을 만든다음 이식하면 자꾸 크래시가 일어나서 답답하던 참이었거든요.

**Comment by dmc31a42** [comment]
실제로 app.info 이 없어서 문제였던가요? 그러면 게임 폴더를 찾는 매커니즘을 바꿔야해서요

**Comment by MoorDev** [comment]
Unity5.3으로 만들어진 게임들을 확인한 결과 app.info란 파일은 존재하지 않았습니다.
TheRoom, TheRoomTwo, 그리고 제가 임의로 만든 Unity5.3게임들 전부 app.info란 파일이 존재하지 않습니다. 
Unity5.3 이전부터 그랬는지는 모르겠지만 app.info파일이 없어진듯 합니다.

**Comment by dmc31a42** [comment]
2017, 2018버전은 확실히 있습니다 최근에 생긴것으로 보입니다. 일단 제기된 버그 하나와 플러그인 추가로 기록해두고, 변경사항있으면 알려드릴께요

**Comment by dmc31a42** [comment]
일단 해당 게임을 불러올 수 없는 문제를 고치고, 불러오기에 실패하였다면 메세지를 띄우게 처리하였습니다. 확인해보시기 바랍니다. NGUI 플러그인은 바로 개발에 착수할께요.
