### ISSUE TITLE
FontAsset 관련하여 여쭈어볼 것이 있습니다.

### ISSUE THREAD

**Issue by Gnbrkm41** [dmc31a42/UnityL10nTool#12]
![image](https://user-images.githubusercontent.com/42944058/48924359-6182d900-eefa-11e8-8dce-21ed66caebcf.png)
sharedassets0.asset 파일 내에 게임 내에서 사용되는 폰트 파일이 6개 있습니다. 게임 내에서 글을 원어로 표시할 때엔 정상적으로 나오나 한국어로 바꾸어 표시할 시 굴림체로 표시되는 문제가 있습니다. 해당 문제를 해결할 때 이 프로그램을 사용할 수 있을지요?

간단한 사용법이라도 혹시 설명해주실 수 있을지 싶습니다. 혹시나 싶어 툴 내에서 프로젝트 연 후 어찌 나오는 지 올려봅니다.
![2018-11-23 083157](https://user-images.githubusercontent.com/42944058/48924356-5def5200-eefa-11e8-8cea-f06bf6777ea0.jpg)

P.S. Add는 비활성화됐는데 Edit이나 Delete 누르면 아직도 팅깁니다... :)

**Comment by Gnbrkm41** [comment]
혹시 #10에 하신 말과 관련이 있는 건가요? 여기에서 뭔가 더 떠야 하는건지 어떤지 써 본적이 없으니 알질 못하겠네요.
>...
> 현재 폰트엔진 지원현황은 TextMesh Pro 만 지원하고
> 2D ToolKit, 유니티 자체 폰트 등을 지원할 예정입니다.
>...

**Comment by dmc31a42** [comment]
일단, 현재 TextMesh Pro 플러그인에서 사용하는 폰트(Monobehaviour TMPro_FontAsset) 만 지원하는 상황입니다.

Font(유니티 기본 폰트)는 아직 지원을 못하고 있습니다.(제 현재 개인사정때문에 급한일이 중간에 껴서 해당 기능 개발이 지연되고 있습니다.)

아무것도 보이지 않는 것은 본문에서 이야기해주신 #10번에 언급된 부분때문인 것이 맞습니다.

일단 급한일이 마무리되는 다음주 수요일부터 #11 (NGUI에서 사용하는 폰트 지원)과 더불어 유니티 기본 폰트 지원도 같이 진행하도록하고, 두 기능 개발이 완료되는대로 사용법도 정리해서 올릴 예정입니다.
업데이트되면 본 이슈를 통해 다시 이야기해드리겠습니다.

**Comment by dmc31a42** [comment]
그리고 선택된 항목이 없으면 Edit하고 Delete부분도 막아야하는데 까먹고 놔뒀네요

**Comment by dmc31a42** [comment]
@Gnbrkm41 폰트 지원 및 매뉴얼에 관해서 두분이 거의 동시에 물어보신 것도 있고 NGUI 폰트 플러그인 개발이 베타 단계가 되어 다음 지원 목표인 유니티 기본 폰트 지원과 관련하여 일단 제가 정한 작업 순서를 말씀드립니다. 
NGUI 폰트 테스트와 FontPlugin 매뉴얼 작성, NGUI 폰트 플러그인 사용법 작성, 빌드와 패처 사용법 작성을 병행함->Unity 기본 폰트(다이나믹 로드만, 비트맵은 추후에) 플러그인 지원 개발->Unity 기본 폰트 플러그인 테스트 및 매뉴얼 작성->전체 매뉴얼 작성 순으로 이루어질 것입니다.

**Comment by dmc31a42** [comment]
유니티 기본 폰트 교체 플러그인 개발을 완료하였습니다. 확인 후 테스트 해보시기 바랍니다.
사용할 폰트는 Plugins\FontPlugins\UnityDefaultFont 폴더안에 ttf 파일을 넣으시면 됩니다.

**Comment by Gnbrkm41** [comment]
잘 되는 것 같습니다.
