### ISSUE TITLE
Visual C++ 2010 Redistributable include

### ISSUE THREAD

**Issue by dmc31a42** [dmc31a42/UnityL10nTool#17]
msvcp100.dll, msvcr100.dll
.NET framework 4.5가 없는 Windows 7 에서 설치할 것인지 물어보는지 확인.

**Comment by newhabi** [comment]
요건 언제쯤 업데이트될까요?

**Comment by dmc31a42** [comment]
아마 오늘 중으로 업데이트 될 겁니다.

**Comment by newhabi** [comment]
감사합니다

해당업데이트 후엔 빌드 프로그램 단독으로 패치가 가능한거죠?

**Comment by dmc31a42** [comment]
네
