### ISSUE TITLE
csv파일 개행 관련 문의드립니다

### ISSUE THREAD

**Issue by newhabi** [dmc31a42/UnityL10nTool#20]
낙원님의 도움으로 언어파일을 열어 하나씩 수정하고 있는데

현재 진행중인 csv번역에서, \n을 입력하여도 개행이 되지 않는 문제가 있습니다

예를들어서

이 연합국에서

당신의 활약이 시작된다 를

이 연합국에서 \n 당신의 활약이 시작된다

또는

"\"이 연합국에서 \n 당신의 활약이 시작된다""

"이 연합국에서 \n 당신의 활약이 시작된다"

"" 이 연합국에서 \n 당신의 활약이 시작된다""

이렇게 넣어도 개행 변경이 안되네요

동일한 파일 안의 원문은 개행이 제대로 작동하는데 제가 번역한 부분만 작동하지 않습니다

 혹시 어느부분이 문제인지 알수있을까요?

**Comment by dmc31a42** [comment]
해당 부분이 화면에 어떻게 표시되는지 스크린샷과 작성한 파일 원본을 주시면 확인해보겠습니다.

**Comment by newhabi** [comment]
![aurigan](https://user-images.githubusercontent.com/45526125/49516840-e51acd80-f8dd-11e8-988a-0bbfd8653862.png)
![kurita](https://user-images.githubusercontent.com/45526125/49516842-e51acd80-f8dd-11e8-91e6-5bb02764cf9d.png)
[strings_fr-FR.zip](https://github.com/dmc31a42/UnityL10nTool/files/2648994/strings_fr-FR.zip)

스크린샷과 해당 스크립트 입니다.

**Comment by dmc31a42** [comment]
이거 어떻게 하면 이 곳까지 들어갈 수 있죠?

**Comment by newhabi** [comment]
게임 실행하신후에, 캠페인, 새 게임 하시고 동영상 넘어가시면

바로 나옵니다

**Comment by newhabi** [comment]
맨 위가 첫 화면, 다음을 누르면 바로 아래화면이 나옵니다

**Comment by dmc31a42** [comment]
첫번째 스샷은 원문(100% 원문)으로도 깨지구요, 두번째꺼는 원문에선 제대로 \n이 먹네요

**Comment by newhabi** [comment]
프랑스어 기반이라 그런지 다른 텍스트들도 깨지는곳이 생각보다 있더라구요

찾아보니 포럼에선 번역기 돌렸냐고 항의하는 글이 좀 있었습니다

명색이 한글화 할려고 기술지원까지 받았는데 저런식으로 하는거보단 좀더 깔끔하게 하는게 나을거같아서

이것저것 시도해봤는데 잘 안되네요

중간에 들어가는 강조표시되는 텍스트 [[DM.BaseDescriptionDefs[LoreAuriganReach]Aurigan Reach]]

이런부분도 단순 텍스트 변경만 가지고는 안먹어서 일단 패스하면서 진행하고 있습니다

**Comment by dmc31a42** [comment]
두번째 사진에는 원문 자체에 \n 이 없네요 애초에 저 텍스트 박스가 보이는 부분에 결함이 있거나 키값이 결함이 있거나인데 이거는 localization  베타가 지나면 차차 해결될거같아보입니다.

**Comment by dmc31a42** [comment]
애초에 손을 대지 않은 원본 자체도 \n이 그대로 표시됩니다. \n 표시 문제는 딱히 우리말화 패치때문에 그런건 아닌거 같습니다.
그래도 번역할때 %나 [ 같은게 있으면 변수같은게 들어가거나 구조를 나타내는 무언가가 있을 수 있으니 이런 특수문자들은 왠만하면 원문에 있는 구조 그대로 적용하길 바랍니다.

**Comment by newhabi** [comment]
답변감사드립니다

정식버전 오르기 전까진 띄어쓰기로 해결해야겠네요

감사합니다 낙원님
