### ISSUE TITLE
공백표시 관련 문의 드립니다

### ISSUE THREAD

**Issue by newhabi** [dmc31a42/UnityL10nTool#21]
안녕하세요 낙원님

다름이 아니고 한글 번역 진행하던중에 추가로 문제가 생겼습니다

커리어나 스토리에 등장하는 함선의 주요메뉴가 폰트 적용이 되지 않고있습니다

![error](https://user-images.githubusercontent.com/45526125/50086476-8855d600-0240-11e9-9683-c89cd534e6a0.png)

![on2](https://user-images.githubusercontent.com/45526125/50086477-8855d600-0240-11e9-9ebc-23500350af44.png)

혹시 해당부분 확인 부탁드릴수 있을까요?

**Comment by dmc31a42** [comment]
오늘은 밤 12시 이후에 확인 후 연락드리겠습니다.
당일 확인가능하시면 즉시 피드백해드리고, 내일 확인가능하다면 7시 이후에 피드백해드리겠습니다.

**Comment by newhabi** [comment]
정말감사합니다

내일 확인할수 있을것 같습니다!

**Comment by dmc31a42** [comment]
그리고 그 전에, 제가 표시되는지 확인할 수 있게 지금까지 번역된 언어 파일과 해당 화면까지 어떻게 진행해야하는지 간단한 설명 부탁드립니다.

**Comment by dmc31a42** [comment]
resources.assets 에 있는 폰트를 일부 사용하는 것으로 확인.
#22 버그 발견 및 이 이슈는 닫음.
