### ISSUE TITLE
Unity 4.0 NGUI 폰트 문의 드립니다

### ISSUE THREAD

**Issue by MerHS** [dmc31a42/UnityL10nTool#25]
현재 빵집소녀 한글화 시도중입니다. 

http://gall.dcinside.com/mgallery/board/view/?id=bjsn&no=2293964&page=1

여기서 다운 받을 수 있는데 L10nTool을 실행하면 Unity 게임으로 인식되지 않아 app.info가 없어서 그런 것 같아 만들어서 넣었더니 실행이 일단 되긴 했습니다만 Loading Assets... 에서 크래시가 납니다.

일단 UABE로 확인 및 실험 결과 Unity 4.0.1f2 NGUI Font Atlas 기반 프로그램이고
` sharedassets1.assets`의 `Font atlas` Texture2D 데이터를 읽어와 렌더링 한다는 것은 확인 했습니다.
(대사 텍스트가 그렇고 주요 UI는 통짜 Texture2D입니다)

혹시 이 프로젝트에 대해 폰트를 넣을 수 있는 방안이 있나요?

**Comment by dmc31a42** [comment]
확인 후 연락드리겠습니다.

**Comment by dmc31a42** [comment]
크래시 나는건 어떻게 잡긴했는데, 에셋이 정상적으로 교체되지 않는 문제 때문에 확인중에 있습니다. Unity Assets Bundle Extractor 로도 제대로 교체되지않아 문제 확인에 시간이 걸릴것으로 보입니다.

**Comment by MerHS** [comment]
아마 크래시만 잡으면 font atlas를 수동으로 바꾸는 방식으로 이 쪽에서 한글화가 가능할 것 같습니다.
잘 안되시면 나중에 하셔도 될 것 같습니다.

**Comment by dmc31a42** [comment]
폰트 교체할때는 Glyph 정보와 Atlas 두개를 모두 바꾸어야합니다. 지금 교체 자체는 정상적으로 되나, 게임에서 인식을 못하는 문제가 있어서 계속 수정해보고 있습니다.

**Comment by dmc31a42** [comment]
![image](https://user-images.githubusercontent.com/13437953/50770754-bbcdd280-12cb-11e9-8e03-3bd47dc93d17.png)
무엇이 문제인지 확인했습니다. 한 이틀정도 후에 정리해서 버전업하도록 하죠

**Comment by MerHS** [comment]
고생하셨네요. 감사합니다.

**Comment by MerHS** [comment]
내일 저녁때 시도해보겠습니다. 
텍스트 수정이랑 sprite ui 변경까지는 다 해봤는데 이제 폰트 넣어 보는 것을 해봐야겠네요.

**Comment by MerHS** [comment]
![aa](https://user-images.githubusercontent.com/6321657/51040855-e08fb600-15fb-11e9-99af-ce7bc270b85b.PNG)
현재 이렇게 뜹니다.
L10nTool로 빌드해서 나온 프로그램을 빵집소녀 루트 폴더에 대해 돌렸더니 sharedassets1.assets.mod 파일이 생성되어서 기존 sharedassets1.assets 파일을 생성된 파일로 변경한 뒤 실행시켰습니다.
UABE로 파일 열어서 텍스트 바꾸는 것은 이슈 올리기 전에 해봐서 되는건 알았는데 한글로 하니까 이렇게 뜨네요. 지금 이렇게 바꿔서 올리는게 맞나요?
[level_battlescript_2-lv0-6.txt](https://github.com/dmc31a42/UnityL10nTool/files/2750036/level_battlescript_2-lv0-6.txt)
[level_battlescript-lv0-7.txt](https://github.com/dmc31a42/UnityL10nTool/files/2750037/level_battlescript-lv0-7.txt)

**Comment by MerHS** [comment]
![aa](https://user-images.githubusercontent.com/6321657/51070173-21c9a980-1680-11e9-842c-8a3eed4fcb16.PNG)
재현 성공했습니다. 수고하셨습니다.
