### ISSUE TITLE
씬 및 스크립트에 하드코딩 된 글자 번역 문의

### ISSUE THREAD

**Issue by MerHS** [dmc31a42/UnityL10nTool#26]
현재 거의 작업이 마무리 되었는데 일부 UILabel이나 씬 안의 GameObject에 붙어있는 스크립트에 하드코딩 된 글자의 처리가 필요합니다.

[참조](http://m.dcinside.com/board/bjsn/2700785)

일단 이 툴로 가능한지는 회의적이지만 혹시 저런 글자들을 찾고 수정하는 방법을 아시나요? (UABE 등으로)

**Comment by dmc31a42** [comment]
UABE 툴을 써서 mainData를 열면 의존성있는 모든 에셋을 불러옵니다.
그리고 Tools->Get script information을 클릭하고 어떤 Assembly 파일을 불러올건지 물어보면 취소하면 콘솔창 하나뜨고 읽어오는 작업을 합니다.
다읽은 다음 Type 열을 기준으로 정렬하여 UILabel을 찾구요,
![image](https://user-images.githubusercontent.com/13437953/51252121-53bf7080-19de-11e9-8730-6b4eb25e12d5.png)
저는 FileID가 1 (resources.assets) Path ID가 897인 에셋을 기준으로 설명하자면,
이 에셋을 클릭 후 Export Dump을 클릭하면 txt 또는 json형식으로 내보낼건지 물어봅니다. 
![image](https://user-images.githubusercontent.com/13437953/51252295-cdeff500-19de-11e9-9ec7-4193a549e3ed.png)
UABE json dump (*.json) 을 선택하시고 저장을 하면 다음과 같이 나타낼 수 있습니다.
![image](https://user-images.githubusercontent.com/13437953/51252411-19a29e80-19df-11e9-9842-4971bd5f89fe.png)
수정 후,
![image](https://user-images.githubusercontent.com/13437953/51252500-58d0ef80-19df-11e9-8bb3-453929928ad7.png)
Import Dump를 통해 불러온 후 View Data를 하면 다음과 같습니다.
![image](https://user-images.githubusercontent.com/13437953/51252546-700fdd00-19df-11e9-93b6-011734164353.png)
OK버튼을 누르거나, File->Save 버튼을 누르면 "수정이 된" 에셋을 저장하는 창이 뜹니다. 기존의 에셋을 덮어쓸 수 없기때문에 본래이름.assets.mod 로 저장하고 바꿔치기하면 됩니다.

여기서 못찾은 문장이 있다면 예시로 적어주시면 어떻게 찾는지 알려드리겠습니다.

**Comment by dmc31a42** [comment]
그리고 텍스쳐(이미지)교체와 UILabel과 같은 하드코딩된 문자열을 교체하는 기능도 추가할까요?
지금 본 프로그램을 Win32+macOS+Linux 지원이 되게 하려고 C#기반 Xamarin.Forms로 포팅을 할 예정입니다.
UnityL10nTool.NET에서 이 프로그램에서 지원하지 못했던 텍스쳐 교체, 하드코딩된 문자열 교체, ttf폰트에서 폰트 이미지 생성 등과 같은 기능을 구현하려고 했고, 특별한 일이 없다면 이 UnityL10nTool은 유지보수만 하고 있습니다.
필요하시다면 본 버전에서도 구현하려구요.

**Comment by MerHS** [comment]
그게 가능하다면 굉장히 좋은 툴이 될 것 같네요. 
일단 알려주신 대로 시도해보겠습니다.
