### ISSUE TITLE
UnityL10nTool 설치 질문

### ISSUE THREAD

**Issue by Countermove** [dmc31a42/UnityL10nTool#27]
0.1.9버전입니다. 원하는 게임은 Life is Strange - Before the Storm입니다.
UnityL10nTool.exe를 실행하고 게임을 선택하면 Project폴더가 생성되고 (비어있습니다) 툴이 종료됩니다.

소스코드를 받아서 실행하면 다음과 같은 오류가 출력됩니다. VS2017 사용합니다.

심각도	코드	설명	프로젝트	파일	줄	비표시 오류(Suppression) 상태
오류	C1010	미리 컴파일된 헤더를 찾는 동안 예기치 않은 파일의 끝이 나타났습니다. '#include "stdafx.h"'을(를) 소스에 추가하시겠습니까?	UnityL10nToolCpp	c:\users\count\downloads\unityl10ntool-0.1.9\unityl10ntool\unityl10ntoolapi\inc\jsoncpp.cpp	5385	
오류	C1010	미리 컴파일된 헤더를 찾는 동안 예기치 않은 파일의 끝이 나타났습니다. '#include "stdafx.h"'을(를) 소스에 추가하시겠습니까?	UnityL10nToolCpp	c:\users\count\downloads\unityl10ntool-0.1.9\unityl10ntool\unityl10ntoolcpp\log_util.cpp	223	
오류	C1083	포함 파일을 열 수 없습니다. 'AssetsTools/AssetsFileReader.h': No such file or directory	UnityL10nToolCpp	c:\users\count\downloads\unityl10ntool-0.1.9\unityl10ntool\unityl10ntoolcpp\unityl10ntoolcpp.h	4

**Comment by dmc31a42** [comment]
프로젝트를 직접 컴파일 할 때는 Release x86으로 바꿔서 하시면 오류없이 진행할 수 있습니다.
실행이 제대로 안되는거는 저녁에 확인해보겠습니다.

**Comment by dmc31a42** [comment]
7e0b0c282a47c82cbe8fd663357e2efb1f183131 게임 이름에 : 가 포함되어 생긴 문제로 확인됬습니다. v0.1.10 버전에서 고쳤습니다.

**Comment by Countermove** [comment]
감사합니다, 해결했습니다.
