### ISSUE TITLE
질문입니다

### ISSUE THREAD

**Issue by LATONI** [dmc31a42/UnityL10nTool#29]
0.1.10 버전 사용중입니다.
사용하려는 게임은 Cultist Simulator 입니다

맨처음 new를 누르고 폴더를 지정할때 Cultist Simulator 를 지정하면 바로 툴이종료되고
cultistsimulator_Data를 지정하면 에셋을 불러오다가 툴이 종료되고 프로젝트 폴더에는 게임명 폴더가 생기고 setting.json 한개가 생성됩니다.

프로그래밍에 대한 지식없이 시작해서 더 자세한 정보는 알려드리고 싶어도 어렵습니다....
혹시 제가 할수있는게 있다면 코멘트로 말해주시면 해보겠습니다.

**Comment by dmc31a42** [comment]
지금 밖이어서 내일 오후 이후에 확인해보고 연락드리겠습니다.

**Comment by LATONI** [comment]
넵

**Comment by dmc31a42** [comment]
Cultist Simulator가 유니티 2018.3 버전으로 개발되었는데 해당 데이터베이스가 없어서 생긴 문제였습니다. 데이터베이스 추가하였으니 최신버전을 받으시면 열어보실 수 있으실껍니다.
