### ISSUE TITLE
폰트 지원 종류 문의

### ISSUE THREAD

**Issue by youbeebee** [dmc31a42/UnityL10nTool#30]
안녕하세요. 툴 덕분에 매직 더 개더링 아레나라는 게임을 성공적으로 한글화했습니다. 정말 감사합니다.
(http://gall.dcinside.com/mtg/89238)

추가로 문의할 내용이 있는데요.

툴의 TMPFontAsset에서 지원하는 폰트가  나눔고딕, NotoSans 두 개인데요, 여기에 다른 폰트를 추가할 수 있는 방법이 있나요?

임의의 폰트(*.otf)를 본 툴에서처럼 *.assets.resS로 변경할 수 있는지 문의드립니다.

**Comment by dmc31a42** [comment]
제작 툴을 따로 안 만들어 두었는데, 일단 제가 오늘 내일 해야할 게 있어서 내일 저녁에 다시 말씀드리겠습니다.

**Comment by dmc31a42** [comment]
* 플러그인 구조를 일부 변경하는 것
* 자동으로 폰트를 만들어주는 프로그램을 만드는 데는 시간이 오래 걸려, 수동으로 만드는 방법 매뉴얼 제작
으로 인하여 주말까지 시간이 걸릴 것 같습니다.

**Comment by dmc31a42** [comment]
그리고, 패치 보고 물어볼게 있습니다.
UnityL10nTool은 폰트, 언어 파일 패치 뿐만 아니라 외부 리소스 파일의 패치까지 지원합니다만, UnityL10nTool에서 제공하는 패처가 아닌 패치 된 게임 파일을 배포하는 이유가 있나요?

**Comment by youbeebee** [comment]
그런 기능이 있는줄 몰랐네요(...)
그래서 wiki에 사용법이 적힌 폰트 덮어쓰기 기능만 사용했습니다.

**Comment by dmc31a42** [comment]
일단 아레나쪽 상황 살펴보고 있는데, 타이틀 폰트와  디스크립션 폰트가 서로 바뀌어서 가독성이 안 젛은거면 두개를 서로 바꾸는 방법을 별도로 알려드릴께요.
강좌글은 조금 시간이 걸릴거 같네요

**Comment by youbeebee** [comment]
두 폰트가 바뀌었단건 (내일 새벽에 업뎃 예정인) 공식 한글판에 해당되는 이야기고, 단순 추측이라 실제로 어떨지는 패치가 되어봐야 알 것 같습니다.

공식 한국어가 지원되면 그 다음부턴 폰트만 좀 더 예쁜 걸로 바꿔치는 유저 폰트 패치 형식이 될 것 같습니다.

급한 일은 아니니 여유있게 해주셔도 됩니다.

**Comment by dmc31a42** [comment]
https://github.com/dmc31a42/UnityL10nTool/wiki/Font-Asset-TMPFontAsset-ko-KR 폰트를 추가하는 방법을 추가하여 놓았으니 확인해보시기 바랍니다.

**Comment by youbeebee** [comment]
![default](https://user-images.githubusercontent.com/22887367/52912760-2fb2c000-32f9-11e9-9927-b8488392b662.png)

공유해주신 방법으로 '본명조'를 추가해봤습니다. 잘 동작합니다. 감사합니다!
