### ISSUE TITLE
폰트 교체 문의

### ISSUE THREAD

**Issue by Jjoony** [dmc31a42/UnityL10nTool#32]
안녕하세요.
유니티를 전혀 모르는 상태에서 Asset의 폰트를 바꿔보려고 시도중입니다.
UABE를 사용해서 폰트 에셋의 위치를 찾고, L10nTool을 사용해서 해당 에셋을 열었습니다.
교체하고자 하는 폰트 에셋을 선택하고(NGUI라고 나오더군요) Font Family를 선택한 후 Save, Build를 눌렀습니다.
Project폴더에 생성된 Patcher.exe를 실행하고 게임 폴더를 선택하니 한참 진행되다가 Loading Font Asset Replacer..라는 메시지가 나온후 프로그램이 꺼져버렸습니다.
물론 패치도 실패하였구요..여러번 시도해봐도 동일합니다.
어떻게 하면 좋을까요..?

**Comment by dmc31a42** [comment]
아직 NGUI 에 대한 테스트 사례가 적어서 제가 직접 돌려보면서 버그를 확인해봐야 할것 같습니다.
게임이름이 무엇인가요?

**Comment by Jjoony** [comment]
Journey In Middle Earth라는 게임입니다.
스팀에서 무료로 받을수 있고요...로그파일이 생성된게 있길래 업로드 해봅니다. 
도움이 될지는 모르겠네요..
패치하려고 하는 에셋은 sharedassets2.assets 에 있는 RomicStd-Medium_App02 라는 에셋입니다.
감사합니다.
[UnityL10nTool-20190512.log](https://github.com/dmc31a42/UnityL10nTool/files/3169996/UnityL10nTool-20190512.log)

**Comment by dmc31a42** [comment]
다운 되는 이유는 확인했는데, 예상한 것과 다르게 작동하는 부분이 많아서 고치는데 약 3일정도 걸릴 것 같습니다.

**Comment by Jjoony** [comment]
꽤 복잡한 문제인가보네요..기다릴게요! 감사합니다!

**Comment by dmc31a42** [comment]
3133c83 v0.1.13
패치가 제대로 안되는건 고쳤습니다만, 이 게임 제작한 제작사......음....... 언어 파일 수정하기 꽤 빡셀껍니다. https://blog.nakwonelec.com/2018/03/27/%EC%96%B8%EC%96%B4-%ED%8C%8C%EC%9D%BC/ 의 Mansions of Madness 항목을 참고해보세요

**Comment by Jjoony** [comment]
언어 수정 자체는 이미 성공했는데..폰트 문제인지 한글이 공백도 아니고 아예 없는것처럼 출력이 안되더라구요 ㅜㅜ 
일부러 영문 단어 사이에 한글을 끼워보기도 했는데, 영문은 문제없이 수정이 되어서 나오는데 한글은 흔적도 없더군요..
여튼 새 버전으로 시도해보겠습니다. 감사합니다!

**Comment by Jjoony** [comment]
오오!! 성공했습니다!
정말 감사합니다^^ 행복한 밤 되세요!

**Comment by dmc31a42** [comment]
패치가 실제로 세상을 볼 날을 기대하겠습니다.
