### ISSUE TITLE
Program Not Detecting Some Fonts

### ISSUE THREAD

**Issue by StarvinArtist** [dmc31a42/UnityL10nTool#36]
(Forgive me, I am not experienced, I may be dumb)
Wonderful Program! I am trying many methods to open game up for translations, needing to replace a font to make it possible. I was following the instructions, but there are fonts which are not detected by the program. The font the game uses is "KimberleyBL-Regular", it might be a Truetype font (.ttf) . I can see the Font Asset in UABE, but not UnityL10nTool (Not in NGUI,TMP,or UnityDefault categories)
![Explorer](https://user-images.githubusercontent.com/46736039/59970506-11becb80-9536-11e9-85c7-99a3c8984eec.JPG)
![UABE](https://user-images.githubusercontent.com/46736039/59970507-14212580-9536-11e9-83e9-0ff6b72251a4.JPG)
![UnityL10n](https://user-images.githubusercontent.com/46736039/59970548-facca900-9536-11e9-8c7b-5b25bb3abfad.JPG)
(Only reads fonts in resources.assets and sharedassets50.assets)
Am I doing something wrong? Is it a glitch? Unsupported feature? My stupidity? 
(You may answer in you own language, I can use translator)
Thank you very much! If you need game font files (.dat or .json), I can give you.

**Comment by dmc31a42** [comment]
'KimberleyBL-Regular' seems 'UnityDefaultFont'. That plugin can handle 'Font' and search asset in resources.assets and sharedassets*.assets. Where is 'KimberleyBL-Regular' font exist?

**Comment by StarvinArtist** [comment]
> 
> 
> Where 'KimberleyBL-Regular' font exist?
KimberleyBL-Regular is in 'globalgamemanagers.assets'.

**Comment by dmc31a42** [comment]
I modify for it. please test v0.1.17 https://github.com/dmc31a42/UnityL10nTool/releases/tag/v0.1.17

**Comment by StarvinArtist** [comment]
It seems to work:
![ItWorks](https://user-images.githubusercontent.com/46736039/60103221-35983200-972d-11e9-8e33-3fa766a9c047.JPG)
THANK YOU SO MUCH! You are amazing! Have a wonderful day!
