### ISSUE TITLE
한글이 아예 출력 자체가 안되는 경우

### ISSUE THREAD

**Issue by eyeofinsight** [dmc31a42/UnityL10nTool#39]
안녕하세요.

블로그에 연재하셨던 글 중 언어 파일에 있는 bomber crew의 예시처럼

한글이 깨져서 출력되지 않고 아예 출력 자체가 안되는 경우에 대해선 어떤 방법이 필요한지 궁금합니다.

건드리는 게임은 Nowhere Prophet이란 게임이고

TMPFontAsset 설명을 따라 폰트를 바꿔서 패처를 빌드했을 때도 영어가 깨져서 나오는 것은 둘째 치고 여전히 한글 출력이 되지 않는 것 같습니다.

**Comment by dmc31a42** [comment]
일단 어떻게 작업하셨는지 같이 보면서 하는것이 좋을거 같기에 디스코드로 연락주시면 도와드리겠습니다.

**Comment by eyeofinsight** [comment]
감사합니다. 친추 보냈습니다.
