### ISSUE TITLE
패쳐 적용에 대한 질문이 있습니다.

### ISSUE THREAD

**Issue by TriColorCat3** [dmc31a42/UnityL10nTool#40]
강의하신 글을 읽고 많은 도움을 받고 있습니다.

현재 상황은,
게임 내에 Text 데이터를 찾아 변경해보는 것에는 성공했고,
한글의 경우에는 출력이 되지 않아 폰트 문제인 것으로 예상하고 있습니다.
해당 Text 데이터를 포함한 에셋의 내용으로 MonoBehaviour를 사용한 폰트로 보입니다.
폰트를 교체하고자 개발하신 "UnityL10nTool_v0.1.19" 를 사용했습니다.
폰트는 sharedassets0.assets에 있었으며 Text 데이터는 StreamingAssets 안에 압축되어 있었습니다.
툴에서 Font 항목의 TMPFontAsset 카테고리에 4가지의 폰트가 검색되었고 해당 폰트를 나눔 글꼴 등으로 변경하고자 하였으나 실패한 상황입니다.
Patcher 제작까지는 성공하였고, 빌드된 Patcher의 Plugin 폴더에 폰트 파일도 있는 것은 확인했습니다.
Patcher를 실행하고 게임을 폴더를 지정하면 진행바가 차오르며 진행이 되는 듯 하다가 아무런 피드백 없이 Patcher가 종료되고 게임의 파일(sharedassets0.assets)도 변경되지 않고 당연히 실제 폰트 변경도 되지 않습니다.
실제 폰트는 sharedassets0.assets.resS 안에 있는 것으로 보입니다만, resS파일을 편집하는 방법을 알 수 없어 여기서 진행하지 못하고 있습니다.

Patcher에서 따로 손봐야 하는 것이 있었던 것인지, 혹은 *.resS 파일을 수정할 수 있는 다른 방법이 있는지 궁금합니다.

//추가로 Wiki에 적어주신 가이드의 내용과 제가 진행함에 있어 조금 차이가 있던 부분은 UnityL10nTool_v0.1.19로 불러온 게임 데이터의 Font의 TMPFontAsset  카테고리에서 Add는 있었지만, Edit 버튼은 없었습니다.
그래도 수정 사항(변경 폰트 적용)을 반영하는 것은 Add만으로 되는 것으로 판단하여 그대로 진행하였습니다.

좋은 툴과 좋은 설명을 해주셔서 감사합니다.

**Comment by dmc31a42** [comment]
UnityL10nTool 도구의 문제이므로 이 레퍼지토리로 issue를 이동하였습니다.

**Comment by dmc31a42** [comment]
TMPFont는 비트맵폰트로 글자정보 Glyph 에셋과, Atlas(폰트이미지) 에셋으로 구성되어있는데 이를 손으로 수정하기는 어렵습니다.
패치가 진행되다가 완료문구없이 꺼지는경우 제가 특정 유니티버전에 대한 처리를 잘못해서 그런것이니 패치를 진행하고자 하는 게임의 유니티 버전 또는 게임 이름을 알려주시면 확인후 연락드리겠습니다.

**Comment by TriColorCat3** [comment]
답변 감사드립니다.
게임의 유니티 버전은 확인하지 못하였으나, 게임은 스팀에 등록된 늑대와 향신료 VR (狼と香辛料VR/Spice&WolfVR) 입니다.
https://store.steampowered.com/app/1065970/VRSpiceWolfVR/

시간을 내주셔서 정말 감사합니다.

**Comment by dmc31a42** [comment]
이 게임은 IL2CPP로 빌드후 배포된 게임인 것으로 보이네요.
간단하게 말씀드리면, 윈도우 배포용 유니티게임은 왠만하면 그냥 소스를 들여다볼 수 있어서 제가 폰트나 이것저것 수정할 수 있었는데, 이건 바로는 소스보기가 불가능합니다.
방법은 있으나 이걸 도입하기에는 수정해야할게 많아서 지금 당장은 힘듭니다.
UnityL10nTool을 사용하지 않고 직접 수정해서 테스트 해보시려면 comment달아주세요.

**Comment by TriColorCat3** [comment]
친절한 답변 감사드립니다.
공부의 목적도 있는만큼 시간 되실 때 안내해주시면 감사히 배우겠습니다.

**Comment by dmc31a42** [comment]
수요일 오후 8시 이후에서 목요일 또는 금요일 9시 이후에서 주말에 디스코드로 연락주세요

**Comment by dmc31a42** [comment]
https://www.twitch.tv/videos/468389463 방송분 참고하세요
