### ISSUE TITLE
[Two Point Hospital] 폰트 이상하게 표현 LaEfreeta님 요청

### ISSUE THREAD

**Issue by dmc31a42** [dmc31a42/UnityL10nTool#42]
-  (Won't fix) TMP_Settings에 fallback 폰트를 등록해도 적용되지 않음(크게 중요하지 않음)
- [x] (bug) resources.assets과 sharedassets0.assets 과 같이 다른 assets에 있는 폰트를 한번에 패치하려면 후자의 FileID가 이상하게 기록됨. 결과적으로 assets중 하나의 assets의 폰트만 fallback 폰트를 읽고 나머지는 읽을 수 없음.
- [ ] (bug, enhancement) 폰트교체시 폰트와 연결된 material은 교체할 수 있으나 https://youtu.be/d2MARbDNeaA 동영상에서 보여주는 것과 같이 폰트와 별개로 생성된 material을 사용하는(보통 폰트 기본값과 다른 underlay나 outline을 적용할 때 쓰임) TextMeshPro, TextMeshProUGUI 는 다른 해상도를 가진 atlas를 바라봄으로 아래의 이미지와 같은 문제가 발생할 수 있음. 이는 TextMeshPro, TextMeshProUGUI에 의존된 material이라 폰트에는 확인할 수 있는 방법이 없음. 직접 검색해서 찾아야함. 
![image](https://user-images.githubusercontent.com/13437953/64125378-b2f2b980-cde4-11e9-96fe-e7fffa36f11b.png)

**Comment by dmc31a42** [comment]
15fedec24e4e1b26232d75e273de88fc273a8de3

**Comment by Akintos** [comment]
아 저거 저도 테스트 해보았던 게임인데, 그냥 폰트 생성할때 글자 사이에 여백 많이 주면 됩니다.

**Comment by dmc31a42** [comment]
fix third problem 809c23729586114fe74238350ec88f00967352a5
