### ISSUE TITLE
폰트 변경 후 한글 출력 관련으로 문의 드립니다.

### ISSUE THREAD

**Issue by BENBENNBEN** [dmc31a42/UnityL10nTool#45]
안녕하세요.

제가 한글화 하려는 스팀 게임은 'Little Misfortune' 입니다.

UnityL10nTool (참고로 0.1.23버젼) 로 열었을 때, 
TMPFontAsset도 여러 폰트가 있고 UnityDefaultFont에도 여러 폰트가 있는데
모두 변경했을 때 폰트가 깨지는 에러가 나서 
이번에는 TMPFontAsset들만 변경해봤습니다.

올려주신 TMP 폰트 추가 강의를 따라해서 UnityL10nTool 에 폰트 2 개를 추가했고,
바꾸고 싶은 폰트를 골라서 Apply -> Save -> Build 한 다음 패치를 해서
폰트가 변경이 되었으나 출력이 나올 때도 있고 안 나올 때도 있고 불안정 합니다.

어떻게 해야 되는지 알려주시면 정말 감사하겠습니다!

![Capture1](https://user-images.githubusercontent.com/54956240/64997746-7e780680-d896-11e9-9223-3c6ae09f086d.PNG)
![Capture2](https://user-images.githubusercontent.com/54956240/64997748-8172f700-d896-11e9-8e16-7b1944ffe884.PNG)

**Comment by dmc31a42** [comment]
1. 전부 패치를 했을 때 깨지는건 버그로 보이는데 원인이 무엇인지 짐작은갑니다만, 발생원인을 확인해보려고 데모를 받았는데 출시시간이 임박해서 그런가 라이브러리목록에 뜨지않아서 에셋을 원상복구를 못하고있습니다. 확인하는대로 고치도록할께요.
2. 특수문자로 아이콘을 표현한경우에 폰트를 완전 덮어씌우게 되면 기존의 아이콘을 쓸 수 없어서 TextMeshPro폰트는 fallback 폰트를 추가하는 형태로 패치를 하고있는데 fallback이 먹히지가 않는거 같습니다. 기존의 방식대로 폰트를 덮어씌울 수 있게끔 옵션을 추가해야겠네요.
ps. 참고로 확인을 위해 물어볼 것이 있는데, '폰트가 변경이 되었으나 출력이 나올 때도 있고 안 나올 때도 있고 불안정 합니다.' 이 말의 의미가, 패치를 한번 하고난 이후에 게임을 실행을 몇번 해보면 어떨때는 폰트가 보였다가 어떨때는 안보였다가 한다는건가요 아니면 매번 무결성검사로 원상복구한뒤에 패치를 하고 실행을 해보면 어떨때는 정상적으로 패치가 되었고 어떨때는 패치가 제대로 안되었다 중에 어느 쪽인가요?
ps2. 문장이 담긴 'MonoBehaviour NAT_SpeechManager'을 수정할 때 UABE의 export/import dump txt, json 둘다 버그가 약간 있어서 export dump 한 파일을 그대로 import dump하면 에셋이 무조건 깨질텐데 어떻게 하셨는지요. 저는 폰트가 제대로 나오는지 확인할 때 export raw 로 추출해서 hex에디터로 수정한뒤 import 했었는데요.

**Comment by BENBENNBEN** [comment]
답변 감사합니다. 

전자의 경우 입니다. 첫 메뉴 화면을 고쳤을 때 '설정'만 한글 출력이 안되거나 다시 실행했을 때 다 출력이 안되거나 부분적으로 출력이 되었다가 안되었다가 했습니다.

UABE로 txt 파일로 export dump 추출해서 영어 string이 아니고 일본어 string에 번역한 것을 덮어 씌우는 방식으로 했습니다.
