### ISSUE TITLE
Unsupport Unity version: 2019.1 알림 이후 무한로딩

### ISSUE THREAD

**Issue by JungHanter** [dmc31a42/UnityL10nTool#52]
![image](https://user-images.githubusercontent.com/1428405/74125784-8d7e9d00-4c19-11ea-93ba-e6f2b0c03e8f.png)

위와같은 메시지 이후 예외발생 합니다.
이 이후로는
![image](https://user-images.githubusercontent.com/1428405/74125810-9ff8d680-4c19-11ea-981d-b52f4391b1f4.png)
이 상태로 무한로딩 상황입니다.

**Comment by dmc31a42** [comment]
v0.1.24 에서 유니티 2019.1 버전 관련 파일을 추가하였으니 확인해보시기 바랍니다.
