### ISSUE TITLE
유니티 버전 2019.3 버전은 언제쯤 지원 가능할까요?

### ISSUE THREAD

**Issue by AMJMA** [dmc31a42/UnityL10nTool#58]
현재 사용중인 게임이 업데이트로 인해서 유니티 2019.3으로 바뀌었는지 한글패치 사용이 불가능 해졌습니다.

이전 이슈글에서 확인하여 U2019.1.0f2 파일을 U2019.3.0f2 파일로 이름을 바꾸어 사용도 해보았습니다만 패치 적용중 강제종료만 될 뿐 진전되질 않습니다.

혹시 버전 업데이트는 언제쯤 하실 생각이 있으신지요?

**Comment by dmc31a42** [comment]
유니티 버전 지원은 UABE가 업데이트 되면 바로 업데이트할수있는데, 아직 UABE가 2019.3을 지원 안 하네요
일단 임시조치를 할 수 있는지 확인해보겠습니다.

**Comment by dmc31a42** [comment]
v0.1.25 버전으로 테스트해보시기 바랍니다
