### ISSUE TITLE
텍스트 매쉬 프로 폰트를 찾지 못하는 경우가 있습니다.

### ISSUE THREAD

**Issue by dudckd502** [dmc31a42/UnityL10nTool#62]
안녕하세요.

유니티 게임을 한글화 시도를 하고 있습니다.

스팀에 Mysterium: A Psychic Clue Game 이라는 보드게임입니다.

UABE로 확인을 해 보았는데 resources.assets에는 없고 level 파일에 TMP 폰트가 있는 것을 확인했습니다.

그런데 UnityL10nTool 툴을 사용해도 해당 TMP 폰트를 찾지 못하는 경우가 있습니다.

한번 확인해 주시면 감사하겠습니다.

**Comment by dmc31a42** [comment]
25일 이후에 살펴보겠습니다.

**Comment by dudckd502** [comment]
> 25일 이후에 살펴보겠습니다.

이 툴로는 따로 방법이 없는 건가요?

**Comment by dmc31a42** [comment]
level 어디에 있었는지 사진으로 첨부해주시겠습니까?

**Comment by dmc31a42** [comment]
이 문제를 완화한 버전을 올려두었습니다.
https://github.com/dmc31a42/UnityL10nTool/releases/tag/v0.1.28

**Comment by dudckd502** [comment]
> 이 문제를 완화한 버전을 올려두었습니다.

해당 버전으로 다시 시도를 해본결과 추가로 폰트 목록이 생성되었습니다.

그러나 폰트를 변경할려고 시도 해봤지만 빌드 과정에 폰트 리플레이스 부분에서 더 이상 넘어가지 못하고 강제 종료 되었습니다.

다른 게임으로 테스트 해본 결과 정상적으로 빌드 되는 것으로 보아 해당 게임의 문제 일 수도 있는 거 같습니다.


버전 업을 해주신 것에 대해 감사드립니다.

**Comment by dmc31a42** [comment]
패치할때 오류나는 것도 해결하여 다시 업데이트하였습니다.
https://github.com/dmc31a42/UnityL10nTool/releases/tag/v0.1.29
