### ISSUE TITLE
프로그램 실행 후 경로 선택 시 버전 문제가 발생합니다.

### ISSUE THREAD

**Issue by psmtree** [dmc31a42/UnityL10nTool#74]
안녕하세요 선생님.
우선 프로그래밍에 대한 지식이 없이 질문드려 죄송합니다.
제가 사용한 방법이 잘못되었는지, 아니면 해당 툴의 새로운 버전이 존재하는지 궁금하여 질문드리게 되었습니다.
스팀에 출시된 Potion Craft Demo를 번역하고 싶어서 올려주신 툴을 찾았습니다.
게임 실행 시 Unity를 이용해 제작되었음이 표시됩니다.
올려주신 위키에 내용대로 프로그램을 실행하였지만 아래와 같은 문제가 발생해 도움을 청할 수 있을까 하여 질문드립니다.

경로명 - D:\Steam\steamapps\common\Potion Craft Demo\Potion Craft_Data

Potion Craft Demo폴더 선택 시 아래 메시지가 출력된 후 프로그램이 종료됩니다.

"Unsupport Unity version:
or, copy latest classdatabase file and rename to U(Version).dat"

Potion Craft_Data 폴더 선택시 아래 세 메시지가 순서대로 출력된 후
툴에서 Loading Assets...가 끝나지 않고 계속됩니다.

"Unsupport Unity version:
or, copy latest classdatabase file and rename to U(Version).dat"

"외부 구성 요소에서 예외를 Throw했습니다."

"Error during working. Please report issue at github"

**Comment by dmc31a42** [comment]
유니티 2020.1 버전 이후로 에셋파일의 구조가 바뀌었는데, 현재 개인적인 일로 이에 대응할 업데이트를 하지 못하고있습니다. 
짧게잡으면 2021년 하반기 또는 2022년 이후에 UABE.NET으로 이전하면서 손볼 예정입니다.
많은 양해 바랍니다.

**Comment by psmtree** [comment]
빠르게 답변 주셔서 정말 감사드립니다!
